config/routes.rb
Rails.application.routes.draw do
  resources :doers
  resources :milestones
  resources :goals
  devise_for :users
  resources :users

  # resources :goals do
  #   # end


  root "doers#index"
  # devise_scope :users do
  #  get "/" => 'users/sessions#create'
  # end
  # root "sessions#new"
  # get "all_users" => "users#index"
  # patch "users#update"

end

app/models/doer.rb
class Doer < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


has_many :goals
  # 
  # has_attached_file :image, styles: { medium: "300x300>" , thumb: "100x100>" }
  # validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/



end

app/controllers/doers_controller.rb
class DoersController < ApplicationController
  before_action :set_doer, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /doers
  # GET /doers.json
  def index
    @doers = Doer.all
  end

  # GET /doers/1
  # GET /doers/1.json
  def show
  end

  # GET /doers/new
  def new
    @doer = Doer.new
  end

  # GET /doers/1/edit
  def edit
  end

  # POST /doers
  # POST /doers.json
  def create
    # attr_accessor for 'image_file_name'
    @doer = Doer.new(doer_params)

    respond_to do |format|
      if @doer.save
        format.html { redirect_to @doer, notice: 'Doer was successfully created.' }
        format.json { render :show, status: :created, location: @doer }
      else
        format.html { render :new }
        format.json { render json: @doer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /doers/1
  # PATCH/PUT /doers/1.json
  def update
    respond_to do |format|
      if @doer.update(doer_params)
        format.html { redirect_to @doer, notice: 'Doer was successfully updated.' }
        format.json { render :show, status: :ok, location: @doer }
      else
        format.html { render :edit }
        format.json { render json: @doer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /doers/1
  # DELETE /doers/1.json
  def destroy
    @doer.destroy
    respond_to do |format|
      format.html { redirect_to doers_url, notice: 'Doer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_doer
      @doer = Doer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def doer_params
      params.require(:doer).permit(:name, :bio, :image , :user_id)
    end
end

app/helpers/doers_helper.rb
module DoersHelper
end

app/views/doers/_form.html.erb
<%= form_for @doer, url: users_path do |form| %>
<%= form_with(model: doer, local: true) do |form| %>
  <% if doer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(doer.errors.count, "error") %> prohibited this doer from being saved:</h2>

      <ul>
      <% doer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :doer_name %>
  </div>

  <div class="field">
    <%= form.label :bio %>
    <%= form.text_area :bio, id: :doer_bio %>
  </div>

  <!-- used for uploading images -->
  <div class="field">
      <%= form.label :image %>
      <%= form.file_field :image %>
  </div>

  <div class="field">
    <%= form.label :does_id %>
    <%= form.number_field :user_id, id: :doer_user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
<% end %>

app/views/doers/edit.html.erb
<h1>Editing Doer</h1>

<%= render 'form', doer: @doer %>

<%= link_to 'Show', @doer %> |
<%= link_to 'Back', doers_path %>

app/views/doers/index.html.erb
<h1>""</h1>

<p id="notice"><%= notice %></p>

<div id="welcome">
  <!-- <h1>Welcome to Just did it!</h1> -->
</div>

<table>
  <thead>
    <!-- title design -->
  <center><div class="long-shadow">JUST DID IT!!</div><center>
<link async href="http://fonts.googleapis.com/css?family=Fredoka%20One" data-generated="http://enjoycss.com" rel="stylesheet" type="text/css"/>
<!-- title design -->

    <tr>
      <!-- <th>Name</th> -->
      <!-- <th>Bio</th> -->
      <!-- <th>User</th> -->
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @doers.each do |doer| %>
      <tr>
        <!-- <td><%= doer.name %></td> -->
        <!-- <td><%= doer.bio %></td> -->
        <!-- <td><%= link_to 'Show', doer %></td> -->
        <!-- <td><%= link_to 'Edit', edit_doer_path(doer) %></td> -->
        <!-- <td><%= link_to 'Destroy', doer, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
      </tr>
    <% end %>

<style>
.long-shadow {
  display: inline-block;
  -webkit-box-sizing: content-box;
  -moz-box-sizing: content-box;
  box-sizing: content-box;
  padding: 25px;
  border: none;
  font: normal 60px/1 "Fredoka One", Helvetica, sans-serif;
  color: rgba(255,255,255,1);
  text-align: center;
  -o-text-overflow: clip;
  text-overflow: clip;
  text-shadow: 3px 3px 0 rgba(34,38,40,0.91) , 3px 3px 0 rgba(34,38,40,0.91) , 3px 3px 0 rgba(34,38,40,0.91) , 4px 4px 0 rgba(42,44,45,0.91) , 6px 6px 0 rgba(42,44,45,0.91) , 7px 7px 0 rgba(42,44,45,0.91) , 8px 8px 0 rgba(42,44,45,0.91) , 9px 9px 0 rgba(42,44,45,0.91) , 10px 10px 0 rgba(42,44,45,0.91) , 11px 11px 0 rgba(42,44,45,0.91) , 12px 12px 0 rgba(42,44,45,0.91) , 13px 13px 0 rgba(42,44,45,0.91) , 14px 14px 0 rgba(42,44,45,0.91) , 15px 15px 0 rgba(42,44,45,0.91) , 16px 16px 0 rgba(42,44,45,0.91) , 17px 17px 0 rgba(42,44,45,0.91) ;
   font-size: 97px;
}

</style>

  </tbody>
</table>

<br>
<!-- <p>
<%= link_to 'New Doer', new_doer_path %>
<br>
<%= link_to 'Create a New Goal', new_goal_url %>
</p> -->

app/views/doers/new.html.erb
<h1>New Doer</h1>

<%= render 'form', doer: @doer %>

<%= link_to 'Back', doers_path %>

app/views/doers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @doer.name %>
</p>

<p>
  <strong>Bio:</strong>
  <%= @doer.bio %>
</p>

<%= link_to 'Edit', edit_doer_path(@doer) %> |
<%= link_to 'Back', doers_path %>