config/routes.rb
Rails.application.routes.draw do
  resources :doers
  resources :milestones
  resources :goals
  devise_for :users
  resources :users

  # resources :goals do
  #   # end


  root "doers#index"
  # devise_scope :users do
  #  get "/" => 'users/sessions#create'
  # end
  # root "sessions#new"
  # get "all_users" => "users#index"
  # patch "users#update"

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  has_attached_file :image, styles: { medium: "300x300>" , thumb: "100x100>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]


  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:title, :subtitle, :info, :image , :description)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<div id="form">


<%= form_for @user, html: { multipart: true } do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>



<%= link_to 'Back to MileStone list', users_path %>


  <div class="field">
    <%= form.label :title %>
    <%= form.text_area :title, id: :user_title %>
  </div>

  <div class="field">
    <%= form.label :subtitle %>
    <%= form.text_area :subtitle, id: :user_subtitle %>
  </div>


  <div class="field">
    <%= form.label :name %>
    <%= form.text_area :name, id: :user_name %>
  </div>

  <!-- used for uploading images -->
  <div class="field">
      <%= form.label :image %>
      <%= form.file_field :image %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :user_description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
</div>

app/views/users/edit.html.erb
<h1>""</h1>
<div id="Edit goals">
  <center><h1>Edit Goals</h1><center>
</div>


<%= render 'form', user: @user %>




<br>
<%= link_to 'Show User Details', @user %> |
<!-- links to show view -->

<br>
<%= link_to 'Back user list', users_path %>
<!-- links to back -->

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>


<center><h1>Users Profile</h1><center>



<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Subtitle</th>
      <th>Info</th>
      <th>Url</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= image_tag user.image %></td>
        <td><%= user.description %></td>
        <td><%= link_to 'Show User Details', user %></td>
        <!-- links to show view -->
        <td><%= link_to 'Edit user', edit_user_path(user) %></td>
        <!-- links to edit -->
        <td><%= link_to 'Delete user', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <!-- links to desrtoy -->
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Create new MileStone', new_user_path %>
<!-- links to create new user -->

app/views/users/new.html.erb
<center><h1>Goal Creator</h1><center>
  <!-- image guy running -->
  <div id="guy">
    <img src="https://edc2.healthtap.com/ht-staging/user_answer/reference_image/17120/large/Hip_muscle_weakness.jpeg?1386669779">


  </div>
<!-- end image -->
<!-- image guy2 -->
<div id="guy2">
  <img src="http://images.onhealth.com/images/slideshow/top-10-fitness-facts-s2-illustration-of-brainpower.jpg">
</div>
<!-- end image -->
<%= render 'form', user: @user %>

<br>
<%= link_to 'goals', new_goal_url %> |
<br>
<%= link_to 'Back to MileStone list', users_path %>
<!-- links to back -->

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>your name</strong>
  <%= @user.name %>
</p>


<!-- view helpers for image upload -->
<%= image_tag @user.image.url(:medium) %>

<p>
  <strong>info</strong>
  <%= @user.description %>
</p>

<%= link_to 'Edit MileStone', edit_user_path(@user) %> |
<!-- show edit link -->
<%= link_to 'Back to MileStone list', users_path %>
<!-- shows back link -->