config/routes.rb
Rails.application.routes.draw do
  resources :doers
  resources :milestones
  resources :goals
  devise_for :users
  resources :users

  # resources :goals do
  #   # end


  root "doers#index"
  # devise_scope :users do
  #  get "/" => 'users/sessions#create'
  # end
  # root "sessions#new"
  # get "all_users" => "users#index"
  # patch "users#update"

end

app/models/goal.rb
class Goal < ApplicationRecord

  has_many :milestones
  belongs_to :user

  has_attached_file :image, styles: { small: "64x64", med: "100x100", large: "200x200" }
  validates :image, :attachment_presence => true
  validates_attachment :image, :content_type => { :content_type => /[jpg|png|jpeg|gif]/ }
# belongs_to :doer, required: true
# validates :doer, presence:true
# has_attached_file :image, styles: { medium: "300x300>" , thumb: "100x100>" }
# validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  before_action :set_goal, only: [:show, :edit, :update, :destroy]

  # GET /goals
  # GET /goals.json
  def index
    @goals = Goal.all
  end

  # GET /goals/1
  # GET /goals/1.json
  def show
  end

  # GET /goals/new
  def new
    @goal = Goal.new
  end

  # GET /goals/1/edit
  def edit
  end

  # POST /goals
  # POST /goals.json
  def create
    @goal = Goal.new(goal_params)
    # @goal.user_id = current_user.id
    # # respond_to do |format|
    #   if @goal.save
    #     format.html { redirect_to @goal, notice: 'Goal was successfully created.' }
    #     format.json { render :show, status: :created, location: @goal }
    #   else
    #     format.html { render :new }
    #     format.json { render json: @goal.errors, status: :unprocessable_entity }
    #   end
    # end


  if @goal.save
      flash[:success] = "The photo was added!"
      redirect_to root_path
    else
      render 'new'
    end





  end

  # PATCH/PUT /goals/1
  # PATCH/PUT /goals/1.json
  def update
    respond_to do |format|
      if @goal.update(goal_params)
        format.html { redirect_to @goal, notice: 'Goal was successfully updated.' }
        format.json { render :show, status: :ok, location: @goal }
      else
        format.html { render :edit }
        format.json { render json: @goal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /goals/1
  # DELETE /goals/1.json
  def destroy
    @goal.destroy
    respond_to do |format|
      format.html { redirect_to goals_url, notice: 'Goal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_goal
      @goal = Goal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def goal_params
      params.require(:goal).permit(:name, :length, :image, :description, :user_id)
    end
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/views/goals/_form.html.erb
<%= form_for @goal, html: { multipart: true } do |form| %>

<%= form_with(model: goal, local: true) do |form| %>
  <% if goal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(goal.errors.count, "error") %> prohibited this goal from being saved:</h2>

      <ul>
      <% goal.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :goal_name %>
  </div>

  <div class="field">
      <span class= "hide"><%= form.label :user_id %></span>
      <%= form.hidden_field :user_id, id: :goal_user_id, value: current_user.id%>
  </div>

  <div class="field">
    <%= form.label :length %>
    <%= form.number_field :length, id: :goal_length %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :goal_description %>
  </div>


    <!-- used for uploading images -->
    <div class="field">
        <%= form.label :image %>
        <%= form.file_field :image, id: :goal_image %>
    </div>

    <div class="actions">
      <%= form.submit %>
    </div>

<% end %>
<% end %>

app/views/goals/edit.html.erb
<h1>""</h1>
<h1>Editing Goal</h1>

<%= render 'form', goal: @goal %>

<%= link_to 'Show', @goal %> |
<%= link_to 'Back', goals_path %>

app/views/goals/index.html.erb
<center><h1>""</h1><center>
<p id="notice"><%= notice %></p>

<!-- <center><h1>Goals</h1><center> -->

<table>
  <thead>
    <!-- title name -->
    <center><div class="long-shadow">Hall of Fame</div><center>
<link async href="http://fonts.googleapis.com/css?family=Fredoka%20One" data-generated="http://enjoycss.com" rel="stylesheet" type="text/css"/>
<!-- title name -->


  <tr>
      <th>Name</th>
      <th>Length</th>
      <th>Description</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>

    <% @goals.each do |goal| %>
      <tr>
        <td><%= goal.name %></td>
        <td><%= goal.length %></td>
        <td><%= goal.description %></td>
        <td><%= link_to image_tag(goal.image.url(:med)), goal.image.url %></td>
        <td><%= link_to 'Show', goal %></td>
        <td><%= link_to 'Edit', edit_goal_path(goal) %></td>
        <td><%= link_to 'Destroy', goal, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
    <style>
    .long-shadow {
  display: inline-block;
  -webkit-box-sizing: content-box;
  -moz-box-sizing: content-box;
  box-sizing: content-box;
  padding: 25px;
  border: none;
  font: normal 60px/1 "Fredoka One", Helvetica, sans-serif;
  color: rgba(255,255,255,1);
  text-align: center;
  -o-text-overflow: clip;
  text-overflow: clip;
  text-shadow: 3px 3px 0 rgba(34,38,40,0.91) , 3px 3px 0 rgba(34,38,40,0.91) , 3px 3px 0 rgba(34,38,40,0.91) , 4px 4px 0 rgba(42,44,45,0.91) , 6px 6px 0 rgba(42,44,45,0.91) , 7px 7px 0 rgba(42,44,45,0.91) , 8px 8px 0 rgba(42,44,45,0.91) , 9px 9px 0 rgba(42,44,45,0.91) , 10px 10px 0 rgba(42,44,45,0.91) , 11px 11px 0 rgba(42,44,45,0.91) , 12px 12px 0 rgba(42,44,45,0.91) , 13px 13px 0 rgba(42,44,45,0.91) , 14px 14px 0 rgba(42,44,45,0.91) , 15px 15px 0 rgba(42,44,45,0.91) , 16px 16px 0 rgba(42,44,45,0.91) , 17px 17px 0 rgba(42,44,45,0.91) ;
  font-size: 96px;
}

tr{
  display:flex;
  justify-content: space-between;
}

td{
  display:flex;
  justify-content: space-between;
}
tbody{
  background-image: url("https://wplook.com/wp-content/uploads/2014/11/stereoclub-disco.jpg");
}

    </style>
  </tbody>
</table>

<br>


<%= link_to 'MileStone', new_milestone_url %> |
<br>
<%= link_to 'New Goal', new_goal_path %>

app/views/goals/new.html.erb
<h1>""</h1>
<h1>New Goal</h1>

<%= render 'form', goal: @goal %>
<br>
<%= link_to 'MileStone', new_milestone_url %> |
<br>
<%= link_to 'Back', goals_path %>

app/views/goals/show.html.erb
<h1>""</h1>

<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @goal.name %>
</p>

<p>
  <strong>Length:</strong>
  <%= @goal.length %>
</p>

<p>
  <strong>Description:</strong>
  <%= @goal.description %>
</p>

<p>
  <strong>Image:</strong>
  <%= link_to image_tag(@goal.image.url(:med)), @goal.image.url %>
</p>

<%= link_to 'Edit', edit_goal_path(@goal) %> |
<%= link_to 'Back', goals_path %>